### ISSUE TITLE
 raise exceptions.FilthMergeError("text length isn't consistent")

### ISSUE THREAD

**Issue by Gilmargolin** [LeapBeyond/scrubadub#26]
Need help with your great library scrubadub
I am getting this error:
Traceback (most recent call last):
  File "scrub_pii", line 23, in <module>
    main()
  File "scrub_pii", line 19, in main
    scrub()
  File "scrub_pii", line 14, in scrub
    df["message"] = df["message"].apply(lambda x:scrubadub.clean(unicode(x,'utf-8')))
  File "/Library/Python/2.7/site-packages/pandas/core/series.py", line 2220, in apply
    mapped = lib.map_infer(values, f, convert=convert_dtype)
  File "pandas/src/inference.pyx", line 1088, in pandas.lib.map_infer (pandas/lib.c:62658)
  File "scrub_pii", line 14, in <lambda>
    df["message"] = df["message"].apply(lambda x:scrubadub.clean(unicode(x,'utf-8')))
  File "/Library/Python/2.7/site-packages/scrubadub/**init**.py", line 16, in clean
    return scrubber.clean(text, **kwargs)
  File "/Library/Python/2.7/site-packages/scrubadub/scrubbers.py", line 58, in clean
    for next_filth in self.iter_filth(text):
  File "/Library/Python/2.7/site-packages/scrubadub/scrubbers.py", line 93, in iter_filth
    filth = filth.merge(next_filth)
  File "/Library/Python/2.7/site-packages/scrubadub/filth/base.py", line 50, in merge
    return MergedFilth(self, other_filth)
  File "/Library/Python/2.7/site-packages/scrubadub/filth/base.py", line 63, in **init**
    self._update_content(b_filth)
  File "/Library/Python/2.7/site-packages/scrubadub/filth/base.py", line 90, in _update_content
    raise exceptions.FilthMergeError("text length isn't consistent")

**Comment by deanmalmgren** [comment]
Thanks for using scrubadub @Gilmargolin! Sorry you've run into a bit of trouble here.

`FilthMergeError`'s occur when two different types of filth (*e.g.*, `NameFilth` and `EmailFilth` are detected in the same location). I'm not sure what about your example is causing the text length to be inconsistent. Can you share a simple example that is replicating the problem?
